### ISSUE TITLE
Sidenav plugin cannot be destroyed and recreated

### ISSUE THREAD

**Issue by jbalsas** [liferay/lexicon#116]
The `Sidenav` plugin does not have an API to destroy instances. This is particularly harmful in SPA environments, where the plugin needs to be destroyed upon navigation and instantiated again.

In particular, https://github.com/liferay/lexicon/blob/master/src/js/side-navigation.js#L676 makes new instantiations fail because the reference to the toggler to be destroyed is kept in the document.

**Comment by pat270** [comment]
Fixed at https://github.com/liferay/lexicon/commit/c800d4cf112b0169edf438a9b4cd00d0015eda08
