### ISSUE TITLE
The "x" displayed in IE for Navbar is inconsistent

### ISSUE THREAD

**Issue by jonmak08** [liferay/lexicon#117]
The IE input clear field button's size is inconsistent in the navbars.

![image](https://cloud.githubusercontent.com/assets/860951/12563169/b59e033c-c35d-11e5-9ba4-bf41d34f8192.png)

![image](https://cloud.githubusercontent.com/assets/860951/12563190/ddc148c4-c35d-11e5-8bc0-bf28490457a5.png)

**Comment by natecavanaugh** [comment]
Merged into develop :)
