### ISSUE TITLE
Link source with live demo and live demo with source

### ISSUE THREAD

**Issue by merlos** [liferay/lexicon#123]
Could you please link both sites: the one with the live demo (http://liferay.github.io/lexicon/) and the source code (https://github.com/liferay/lexicon/).

Visitos cannot directly access the source code site from the demo site neither access the demo site from the source code site.

Thanks. Juan

**Comment by pat270** [comment]
Hi Juan,

Yes we can do that. I will add this to my to do. Thanks!

Patrick
