### ISSUE TITLE
modal styles causes document to scroll to top in Chrome

### ISSUE THREAD

**Issue by mjbradford89** [liferay/lexicon#132]
This can be reproduced at http://liferay.github.io/lexicon/content/modals/ and also in liferay-portal.  I think this is caused by the styles from the class `modal-open` that is appended to the body.

1. Navigate to http://liferay.github.io/lexicon/content/modals/.
2. Scroll down a bit and click the 'Large Modal' button or the 'Full Screen Modal' button.
3. Close the modal.

Result: The page is scrolled back to the top.

Note: It seems like for the bottom 3 buttons on the Modal demo page, the bootstrap modal component is resetting the scroll position after the modal is closed.

**Comment by natecavanaugh** [comment]
Thanks @mjbradford89 

@pat270 this is being caused by the `modal-open` class being defined here:
https://github.com/liferay/lexicon/blob/master/src/scss/lexicon-base/_modals.scss#L83-L89

I can't remember why that was added. Do you happen to remember?

**Comment by pat270** [comment]
Hey @natecavanaugh and @mjbradford89, those styles were added specifically for ios. Long content under the modal would be scrollable without position fixed because ios doesn't respect overflow hidden on the body. I'll find a work around.
