### ISSUE TITLE
Add a CDN usage for the CSS and JS files.

### ISSUE THREAD

**Issue by djalmaaraujo** [liferay/lexicon#160]
I think this is helpful to other users who wants to use lexicon outside of the liferay context.

**Comment by pat270** [comment]
Hey @djalmaaraujo, Sorry I'm so late replying to this. I will talk to Nate about setting up a CDN. If you want to test drive Lexicon outside of Liferay's context, you can link directly to the css files on Lexicon's GitHub page.

Atlas: 
`<link rel="stylesheet" href="http://liferay.github.io/lexicon/css/atlas-font-awesome.css">`

Lexicon Base: 
`<link rel="stylesheet" href="http://liferay.github.io/lexicon/css/lexicon-font-awesome.css">`

**Comment by djalmaaraujo** [comment]
Ok then. Waiting for this :)

thaanks

**Comment by natecavanaugh** [comment]
@djalmaaraujo We just published Lexicon up to NPM (which includes both the src and the build files), and there's an NPM CDN provider, so you can link to the package with https://npmcdn.com/lexicon-ux@1.0.1/build/css/atlas.css
For example, if you wanted the Atlas theme. If you just want the lexicon-base package, you can link to:
https://npmcdn.com/lexicon-ux@1.0.1/build/css/lexicon-base.css

The JS is located under the js directory, you can access the icons at either the SVG sprite here: https://npmcdn.com/lexicon-ux@1.0.1/build/images/icons/icons.svg
Or individually with something like:
https://npmcdn.com/lexicon-ux@1.0.1/build/images/icons/home.svg

Hope that helps!

**Comment by djalmaaraujo** [comment]
@natecavanaugh That's nice, my idea of the issue is to put on the readme, so everyone can easily use. :)

**Comment by beppe1992** [comment]
Hi,
i try to download npm package, but i have an error because in atlas.css there's a reference to ../fonts/bootstrap/glyphicons-halflings-regular.eot, but this file not exist in build directory.

**Comment by pat270** [comment]
@beppe1992 Thanks for reporting this! I filed a separate issue for it.
