### ISSUE TITLE
Add variables for sidenav transition values

### ISSUE THREAD

**Issue by Robert-Frampton** [liferay/lexicon#170]
When there is a fixed element on the page and I want it to transition with a sidenav, it's hard to figure out the transition duration and timing function used by the sidenav. So it would be useful to set those values with variables that can be used elsewhere.

So variables specifically for `0.5s` and `ease` in _side_navigation.scss.

```scss
.sidenav-transition,
.sidenav-transition .sidenav-content,
.sidenav-transition .sidenav-menu-slider,
.sidenav-transition .sidenav-menu-slider .sidenav-menu {
	@include transition(all 0.5s ease);
}
```

**Comment by pat270** [comment]
Fixed by #176
