### ISSUE TITLE
Add link to the website in the repo metadata

### ISSUE THREAD

**Issue by yuchi** [liferay/lexicon#174]
You should add a link to https://liferay.github.io/lexicon/ in the repository metadata, and probably a short description wouldn’t hurt.

**Comment by natecavanaugh** [comment]
Heya Pier,
Thanks for the issue. When you say metadata, do you mean the package.json, or something else?

**Comment by yuchi** [comment]
Mostly this: 
<img width="283" alt="schermata 2016-05-11 alle 00 04 18" src="https://cloud.githubusercontent.com/assets/646609/15163949/f3815ef4-170b-11e6-9f47-f215d0048c75.png">

:)

**Comment by natecavanaugh** [comment]
Ahhh, gotcha!
Thanks :)

**Comment by natecavanaugh** [comment]
Fixed :)
